### ISSUE TITLE
Attribution i kartlager beter sig knasigt när man startar första gången

### ISSUE THREAD

**Issue by danielmartling** [danielmartling/trappermapper#13]
Efter start:
![bild](https://github.com/danielmartling/trappermapper/assets/140479913/46624e3b-0aae-44ab-83e9-a61a2a84848c)

Efter byte till satellit
![bild](https://github.com/danielmartling/trappermapper/assets/140479913/03c3735b-3407-4b18-9c8a-21022822e0e7)

Efter byte tillbaka till OSM
![bild](https://github.com/danielmartling/trappermapper/assets/140479913/fd4eaa11-267f-427a-a76c-b68b2d399ae4)

**Comment by garakangas** [comment]
Det knasiga är direkt när sidan läses in, då visas båda lagrens "attribution" info "OpenStreetMap contributors" för OSM lagret samt  "Tiles © Esri — Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community" för satellitbilden.

Har inte tid att kika nu, men min gissning är att vi måste "välja" rätt lager bättre direkt när sidan öppnas.

**Comment by danielmartling** [comment]
Har fixat detta nu.
![image](https://github.com/danielmartling/trappermapper/assets/140479913/8c223571-4e63-4140-b32b-f4bc707c8819)
