### ISSUE TITLE
Titelrutan ligger ovanför filterikonen

### ISSUE THREAD

**Issue by danielmartling** [danielmartling/trappermapper#18]
Skriv CSS för att fördela utrymmet bättre för små skärmar. Hitta z-index för filterknappen och lägg längst fram som nödlösning?

**Comment by garakangas** [comment]
Flexbox är ofta en lösning som funkar bra när skillnaderna på skärmstorlek inte är jättestora (olika storlek på mobiler, eller 1080p vs 1440p, etc). Gör det lättare att dynamiskt anpassa storleken på olika objekt

**Comment by danielmartling** [comment]
Stänger denna som fixad. Loggan är nu i nedre vänstra hörnet.
